In [1]:
%matplotlib qt5

In [2]:
import numpy as np
import matplotlib.pyplot as plt
# Though the following import is not directly being used, it is required
# for 3D projection to work
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.metrics.pairwise import euclidean_distances

import EKNNclus

[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0.5]
 [ 0.   0.   1.   0.5]
 [ 0.   0.5  0.5  1. ]]
center:[  1.85037171e-17   4.66666667e-01   2.33333333e-01   3.00000000e-01]


In [3]:
iris = datasets.load_iris()

In [4]:
X=iris.data
y = iris.target

In [5]:
dist_mat = euclidean_distances(X,X)

In [9]:
dist_mat

array([[ 0.        ,  0.53851648,  0.50990195, ...,  4.45982062,
         4.65080638,  4.14004831],
       [ 0.53851648,  0.        ,  0.3       , ...,  4.49888875,
         4.71805044,  4.15331193],
       [ 0.50990195,  0.3       ,  0.        , ...,  4.66154481,
         4.84871117,  4.29883705],
       ..., 
       [ 4.45982062,  4.49888875,  4.66154481, ...,  0.        ,
         0.6164414 ,  0.64031242],
       [ 4.65080638,  4.71805044,  4.84871117, ...,  0.6164414 ,
         0.        ,  0.76811457],
       [ 4.14004831,  4.15331193,  4.29883705, ...,  0.64031242,
         0.76811457,  0.        ]])

In [6]:
clus = EKNNclus.EKNNclus_Th(X, K = 30,D = dist_mat, ntrials=20, y0 = list(range(X.shape[0])),tr = True)

0 1 143 16
0 2 24 5
0 3 3 5
0 4 0 5
1 1 140 17
1 2 32 7
1 3 10 5
1 4 1 5
1 5 0 5
2 1 142 14
2 2 17 4
2 3 6 4
2 4 4 3
2 5 0 3
3 1 142 13
3 2 17 5
3 3 1 5
3 4 0 5
4 1 144 15
4 2 22 6
4 3 10 4
4 4 0 4
5 1 142 15
5 2 26 4
5 3 3 3
5 4 0 3
6 1 141 21
6 2 25 5
6 3 0 5
7 1 143 18
7 2 35 4
7 3 0 4
8 1 144 14
8 2 22 5
8 3 1 4
8 4 0 4
9 1 144 21
9 2 33 6
9 3 8 4
9 4 4 4
9 5 3 4
9 6 2 4
9 7 0 4
10 1 145 11
10 2 11 4
10 3 1 4
10 4 0 4
11 1 145 9
11 2 18 4
11 3 2 4
11 4 1 4
11 5 0 4
12 1 144 14
12 2 16 4
12 3 1 4
12 4 0 4
13 1 141 20
13 2 29 7
13 3 14 5
13 4 0 5
14 1 147 13
14 2 23 3
14 3 0 3
15 1 143 12
15 2 14 4
15 3 0 4
16 1 141 15
16 2 32 6
16 3 6 5
16 4 1 5
16 5 0 5
17 1 143 12
17 2 21 6
17 3 8 5
17 4 1 4
17 5 0 4
18 1 145 12
18 2 15 4
18 3 0 4
19 1 143 18
19 2 26 6
19 3 2 6
19 4 0 6


In [7]:
np.unique(clus)

array([0, 1, 2])

In [8]:
fignum=1
fig = plt.figure(fignum, figsize=(4, 3))
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

labels = clus

ax.scatter(X[:, 3], X[:, 0], X[:, 2],
               c=labels.astype(np.float))#, edgecolor='k')

ax.w_xaxis.set_ticklabels([])
ax.w_yaxis.set_ticklabels([])
ax.w_zaxis.set_ticklabels([])
ax.set_xlabel('Petal width')
ax.set_ylabel('Sepal length')
ax.set_zlabel('Petal length')
#ax.set_title(titles[fignum - 1])
ax.dist = 12
fignum = fignum + 1

# Plot the ground truth
fig = plt.figure(fignum, figsize=(4, 3))
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

for name, label in [('Setosa', 0),
                    ('Versicolour', 1),
                    ('Virginica', 2)]:
    ax.text3D(X[y == label, 3].mean(),
              X[y == label, 0].mean(),
              X[y == label, 2].mean() + 2, name,
              horizontalalignment='center',
              bbox=dict(alpha=.2, edgecolor='w', facecolor='w'))
# Reorder the labels to have colors matching the cluster results
y = np.choose(y, [1, 2, 0]).astype(np.float)
ax.scatter(X[:, 3], X[:, 0], X[:, 2], c=y)#, edgecolor='k')

ax.w_xaxis.set_ticklabels([])
ax.w_yaxis.set_ticklabels([])
ax.w_zaxis.set_ticklabels([])
ax.set_xlabel('Petal width')
ax.set_ylabel('Sepal length')
ax.set_zlabel('Petal length')
ax.set_title('Ground Truth')
ax.dist = 12

fig.show()