In [2]:
import numpy as np

from read import read_voter_file, read_score_file, read_order_file
from tools import all_mass_init, flatten_pref_mass_mat

from beliefKMeans import k_means, _k_means_single, silhouette_score


[1546, 1535, 1406, 1457, 1380, 1447, 1412, 1353, 1321, 1244, 1297, 1213, 1194, 1118, 1112, 1077, 1012, 1016, 968, 957, 939, 945, 868, 857, 841, 847, 785, 775, 699, 694, 696, 619, 512, 567, 560, 545, 500, 532, 509, 453, 433, 468, 413, 334, 336, 327, 358, 366, 347, 348, 355, 385, 287, 282, 231, 199, 214, 218, 219, 236, 219, 234, 213, 215, 234, 155, 142, 138, 135, 155, 141, 164, 169, 133, 165, 148, 144, 131, 150, 153, 78, 67, 88, 50, 66, 80, 52, 77, 85, 84, 74, 80, 76, 75, 72, 95, 68, 79, 75, 77]
[0, 1, 3, 5, 6, 2, 4, 7, 8, 10, 9, 11, 12, 13, 14, 15, 17, 16]
1
[3182]
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0.5]
 [ 0.   0.   1.   0.5]
 [ 0.   0.5  0.5  1. ]]
center:[  1.85037171e-17   4.66666667e-01   2.33333333e-01   3.00000000e-01]


In [91]:
vMap = read_voter_file("../data/sushi3-2016/sushi3.com30.udata")
read_score_file("../data/sushi3-2016/sushi3b.com30.10.score", vMap)
read_order_file("../data/sushi3-2016/sushi3b.com30.10.order", vMap)
# candidate list for 40 cand
"""
cand_list=[0, 1, 3, 5, 6, 2, 4, 7, 8, 10, 
           9, 11, 12, 13, 14, 15, 17, 16, 
           18, 19, 21, 20, 22, 23, 25, 24, 
           26, 27, 28, 30, 29, 31, 33, 34, 
           35, 37, 32, 38, 36, 41]
#candidate list for 35 cand

"""
"""
cand_list=[0, 1, 3, 5, 6, 2, 4, 7, 8, 10, 
           9, 11, 12, 13, 14, 15, 17, 16, 
           18, 19, 21, 20, 22, 23, 25, 24, 
           26, 27, 28, 30, 29, 31, 33, 34, 35]
"""
#candidate list for 30 cands

cand_list = [0, 1, 3, 5, 6, 2, 4, 7, 8, 10,
             9, 11, 12, 13, 14, 15, 17, 16, 
             18, 19, 21, 20, 22, 23, 25,24, 
             26, 27, 28, 30,]

#cand_list = list(range(100))
#n_item = 40
n_item = 30
#n_item = 100

In [4]:
vMap = read_voter_file("../data/sushi3-2016/artif_inverse_2.udata")
read_score_file("../data/sushi3-2016/artif_inverse_2.score", vMap)
read_order_file("../data/sushi3-2016/artif_inverse_2.order", vMap)
cand_list=[8, 0, 13, 1, 9, 17, 11, 10, 7, 5]
cand_list.sort()
n_item = 10

In [51]:
len(vMap)

12

In [92]:
def cal_pair_in_common(vMap):
    com_mat = np.zeros((len(vMap),len(vMap)))
    for i in vMap.keys():
        for j in vMap.keys():
            com_element=len(set(vMap[i].get_order_b()).intersection(set(vMap[j].get_order_b())))
            #com_mat[i][j] = com_element*(com_element-1)/2
            com_mat[i][j] = com_element
    return com_mat
print(cal_pair_in_common(vMap))

[[ 10.   1.   3. ...,   2.   5.   4.]
 [  1.  10.   3. ...,   4.   5.   3.]
 [  3.   3.  10. ...,   5.   5.   5.]
 ..., 
 [  2.   4.   5. ...,  10.   3.   2.]
 [  5.   5.   5. ...,   3.  10.   4.]
 [  4.   3.   5. ...,   2.   4.  10.]]


In [93]:
n_sample = len(vMap)
vector_size = 16
n_pref_pair = int(n_item*(n_item-1)/2)
X = np.empty((n_sample, n_pref_pair, vector_size),dtype = object)
for k,v in vMap.items():
    X[k] = flatten_pref_mass_mat(all_mass_init(v.get_scores(), v.get_order_b(), cand_list, nbItem = n_item))

In [94]:
from beliefDBSCAN import cal_distances
dist_mat = cal_distances(X, 'jousselme')

In [135]:
del EKNNclus
import importlib
import EKNNclus
EKNNclus = importlib.reload(EKNNclus)
#from EKNNclcus import EKNNclus
labels = EKNNclus.EKNNclus(X,K = 3,dist_mat = dist_mat,common_pair_mat=cal_pair_in_common(vMap),maximum_pair=10, verbose = True)

start initialization
> /home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/EKNNclus.py(176)EKNNclus()
-> if verbose:
(Pdb) print(v)
[[ 0.91629073  0.34841992  0.91629073  0.34841992  0.91629073  0.34841992
   0.91629073  0.34841992  0.15917368  0.15917368  0.15917368  0.15917368]
 [ 0.34841992  0.91629073  0.34841992  0.91629073  0.34841992  0.91629073
   0.34841992  0.91629073  0.13745928  0.13745928  0.13745928  0.13745928]
 [ 0.91629073  0.34841992  0.91629073  0.34841992  0.91629073  0.34841992
   0.91629073  0.34841992  0.15917368  0.15917368  0.15917368  0.15917368]
 [ 0.34841992  0.91629073  0.34841992  0.91629073  0.34841992  0.91629073
   0.34841992  0.91629073  0.13745928  0.13745928  0.13745928  0.13745928]
 [ 0.91629073  0.34841992  0.91629073  0.34841992  0.91629073  0.34841992
   0.91629073  0.34841992  0.15917368  0.15917368  0.15917368  0.15917368]
 [ 0.34841992  0.91629073  0.34841992  0.91629073  0.34841992  0.91629073
   0.34841992  0.91629073  0.13745928  

In [36]:
dist_mat[2][26]

0.13358656676727243

In [16]:
labels[20]

array([ True,  True,  True,  True,  True], dtype=bool)

In [134]:
label_sim = np.zeros((labels.shape[0]))
for i in range(label_sim.shape[0]):
    print(i, np.where(labels[i]==True))
    #label_sim[i] = np.where(labels[i]==True)[0]


0 (array([0, 1, 2]),)
1 (array([0, 1, 2]),)
2 (array([0, 1, 2]),)
3 (array([0, 1, 2]),)
4 (array([0, 1, 2]),)
5 (array([0, 1, 2]),)
6 (array([0, 1, 2]),)
7 (array([0, 1, 2]),)
8 (array([0, 1, 2]),)
9 (array([0, 1, 2]),)
10 (array([0, 1, 2]),)
11 (array([0, 1, 2]),)


In [131]:
for clu in np.unique(label_sim):
    print(np.where(label_sim==clu))

(array([ 2,  7,  8,  9, 10]),)
(array([0, 1, 3, 4, 5, 6]),)
(array([11]),)


K = 2:
1st:
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17,
       19, 21, 22, 23, 24, 27, 28, 30, 31, 34, 35, 36, 37, 40, 41, 42, 43,
       47, 49, 52, 53]),)
(array([14, 18, 20, 25, 26, 29, 32, 33, 38, 39, 44, 45, 46, 48, 50, 51]),)

2nd:
(array([ 1,  4,  5,  7,  9, 11, 13, 18, 19, 25, 26, 27, 28, 30, 36, 40, 45]),)
(array([ 0,  2,  3,  6,  8, 10, 12, 14, 15, 16, 17, 20, 21, 22, 23, 24, 29,
       31, 32, 33, 34, 35, 37, 38, 39, 41, 42, 43, 44, 46, 47, 48, 49, 50,
       51, 52, 53]),)

1st:
array([ 2,  5,  8,  9, 11, 12, 13, 14, 16, 21, 22, 23, 24, 29, 30, 31, 32,
       33, 34, 36, 40, 42, 43, 44, 45, 48, 50, 51]),)
(array([ 3, 17, 26, 27, 41, 49, 53]),)
(array([ 0,  1,  4,  6,  7, 10, 15, 19, 20, 25, 28, 35, 37, 38, 39, 47, 52]),)
(array([18, 46]),)

2nd:
(array([ 0,  2,  3,  4,  6,  7,  8,  9, 11, 14, 15, 16, 17, 18, 21, 22, 23,
       26, 28, 30, 33, 34, 35, 36, 37, 39, 40, 41, 43, 44, 46, 48, 49, 50,
       52, 53]),)
(array([ 1, 10, 12, 24, 27, 38]),)
(array([ 5, 13, 19, 20, 25, 29, 31, 32, 42, 45, 47, 51]),)

3rd:
(array([ 2, 26, 32]),)
(array([20, 21, 42]),)
(array([ 1,  3,  6, 10, 13, 14, 15, 16, 17, 19, 22, 23, 33, 36, 37, 38, 43,
       45, 49, 50]),)
(array([ 0,  4,  5,  7,  8,  9, 11, 12, 18, 24, 25, 27, 28, 29, 30, 31, 34,
       35, 39, 40, 41, 44, 46, 47, 48, 51, 52, 53]),)
       
4th:
(array([ 2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 14, 15, 18, 19, 20, 21, 22,
       23, 25, 26, 27, 28, 29, 30, 31, 33, 36, 37, 39, 42, 43, 44, 51, 52,
       53]),)
(array([ 1,  6, 13, 34, 35, 47, 49]),)
(array([ 0, 16, 17, 24, 40, 46, 50]),)
(array([32, 38, 41, 45, 48]),)

dynamic $\alpha$
1st:

(array([ 2, 44, 53]),)
(array([14, 45]),)
(array([ 4, 13, 17, 20, 38, 52]),)
(array([ 3,  7, 31, 35, 39, 49]),)
(array([ 1, 11, 12, 25, 26, 29, 46, 47]),)
(array([15, 19]),)
(array([ 5,  8,  9, 18, 27, 36, 48]),)
(array([16, 23, 28, 32]),)
(array([ 6, 22, 24, 33, 37, 42, 43, 50, 51]),)
(array([ 0, 10, 21, 30, 34, 40, 41]),)

2nd:
(array([ 2,  4,  5,  7,  8, 16, 21, 22, 24, 31, 32, 41, 42, 43, 47, 48, 50, 53]),)
(array([13, 28, 52]),)
(array([ 6, 25]),)
(array([ 3, 49]),)
(array([ 1, 27]),)
(array([ 9, 12, 14, 17, 18, 23, 29, 39, 44]),)
(array([ 0, 10, 20, 30, 34, 40, 46]),)
(array([26, 33, 37, 45, 51]),)
(array([11, 15, 19, 35, 36, 38]),)

3rd:
(array([ 6, 28]),)
(array([ 1, 26]),)
(array([ 5, 15, 42]),)
(array([ 7,  8, 10, 11, 18, 22, 23, 35, 48]),)
(array([ 2, 12, 13, 19, 20, 21, 24, 29, 30, 33, 34, 37, 39, 41, 43, 46, 51, 52]),)
(array([16, 25, 32, 36]),)
(array([ 0,  4, 17, 27, 47, 53]),)
(array([14, 45]),)
(array([31, 40, 44]),)
(array([ 3, 49]),)
(array([ 9, 38, 50]),)


4th
((array([ 8, 11, 18, 35]),)
(array([14, 17, 20, 23, 28, 31, 39, 50]),)
(array([21, 22, 41]),)
(array([ 1,  3,  4,  9, 15, 24, 25, 38, 43, 45]),)
(array([ 0,  2,  5,  6,  7, 10, 12, 13, 16, 19, 26, 27, 29, 30, 32, 33, 34,
       36, 37, 40, 42, 44, 46, 47, 48, 49, 51, 52, 53]),)

In [81]:
dist_mat

array([[ 0.        ,  0.81009794,  0.        ,  0.81009794,  0.        ,
         0.81009794,  0.        ,  0.81009794,  0.66211317,  0.66211317,
         0.66211317,  0.66211317],
       [ 0.81009794,  0.        ,  0.81009794,  0.        ,  0.81009794,
         0.        ,  0.81009794,  0.        ,  0.75221308,  0.75221308,
         0.75221308,  0.75221308],
       [ 0.        ,  0.81009794,  0.        ,  0.81009794,  0.        ,
         0.81009794,  0.        ,  0.81009794,  0.66211317,  0.66211317,
         0.66211317,  0.66211317],
       [ 0.81009794,  0.        ,  0.81009794,  0.        ,  0.81009794,
         0.        ,  0.81009794,  0.        ,  0.75221308,  0.75221308,
         0.75221308,  0.75221308],
       [ 0.        ,  0.81009794,  0.        ,  0.81009794,  0.        ,
         0.81009794,  0.        ,  0.81009794,  0.66211317,  0.66211317,
         0.66211317,  0.66211317],
       [ 0.81009794,  0.        ,  0.81009794,  0.        ,  0.81009794,
         0.        ,  

In [145]:
knn_ind, knn_dist = EKNNclus.get_KNN(dist_mat, 3)
alpha_mat = cal_pair_in_common(vMap)/10

print(knn_ind,alpha_mat[knn_ind])

[[41 47 46]
 [25 26 47]
 [41  8 42]
 [15 49 14]
 [47 35 12]
 [48 40 47]
 [28 13 25]
 [47 10 26]
 [24  2 18]
 [35 27 44]
 [47 12 35]
 [12 29 19]
 [44 29 47]
 [52 47 17]
 [ 3  2 45]
 [ 3 25 36]
 [30 25 26]
 [52 13 20]
 [23  8 28]
 [12 11 13]
 [12 13 28]
 [41 22 24]
 [21 10 50]
 [18 20 19]
 [ 8 21 43]
 [ 1 12 16]
 [46 47 30]
 [42 47 18]
 [35 10 26]
 [47 12 44]
 [46 16 26]
 [40 41 51]
 [16 36 30]
 [51 10 40]
 [40 21 12]
 [28 10  9]
 [13 38 28]
 [42 47 43]
 [47 36 29]
 [ 2 13 31]
 [34 42 41]
 [21  2 40]
 [50 37 27]
 [37 50 47]
 [12 29 47]
 [15 14 37]
 [26 30 47]
 [29  7 26]
 [40  5 18]
 [ 3 42 12]
 [42 43 37]
 [33 37 16]
 [13 17  2]
 [41  2 21]] [[[ 0.6  0.1  0.6 ...,  0.3  0.3  0.6]
  [ 0.4  0.4  0.3 ...,  0.2  0.4  0.4]
  [ 0.5  0.3  0.3 ...,  0.2  0.4  0.4]]

 [[ 0.   0.6  0.2 ...,  0.3  0.4  0.4]
  [ 0.3  0.5  0.1 ...,  0.3  0.3  0.3]
  [ 0.4  0.4  0.3 ...,  0.2  0.4  0.4]]

 [[ 0.6  0.1  0.6 ...,  0.3  0.3  0.6]
  [ 0.3  0.3  0.6 ...,  0.4  0.3  0.3]
  [ 0.4  0.3  0.5 ...,  0.5  0.4  0

In [155]:
print(knn_ind[0],knn_ind.shape, alpha_mat[0][[41,47,46]], alpha_mat[knn_ind].shape)
knn_alpha = np.zeros(knn_ind.shape)
for i in range(knn_ind.shape[0]):
    knn_alpha[i] = alpha_mat[i][knn_ind[i]]
#print(knn_alpha)
knn_ind[0]*alpha_mat[0][[41,47,46]]

[41 47 46] (54, 3) [ 0.6  0.4  0.5] (54, 3, 54)


array([ 24.6,  18.8,  23. ])

In [1]:
del EKNNclus
import importlib
import EKNNclus
EKNNclus = importlib.reload(EKNNclus)
clus = EKNNclus.EKNNclus_Th(X, K = 5, D = dist_mat, alpha_mat = alpha_mat,ntrials=20, y0 = list(reversed(range(X.shape[0]))),tr = True)
for i in np.unique(clus):
    print(i, np.where(clus==i))

NameError: name 'EKNNclus' is not defined

In [163]:
from beliefKMeans import silhouette_score
print(silhouette_score(X, clus))

nan


/home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/beliefKMeans.py:560: RuntimeWarning: invalid value encountered in true_divide
  sil_samples /= np.maximum(intra_clust_dists, inter_clust_dists)


ntrials = 20, K = 5, y0 increasing list:
1st try: 
0 (array([ 1, 16, 25, 26, 30, 46]),)
1 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 40, 41, 48, 51, 53]),)
2 (array([37, 42, 43, 50]),)
3 (array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 23,
       27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)
2nd try:
0 (array([ 0,  1,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 38, 39, 44, 45,
       46, 47, 49, 51, 52]),)
1 (array([ 2,  5,  8, 21, 22, 24, 34, 40, 41, 48, 53]),)
2 (array([37, 42, 43, 50]),)

3rd try:
0 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 40, 41, 48, 51, 53]),)
1 (array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 23,
       27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)
2 (array([ 1, 16, 25, 26, 30, 46]),)
3 (array([37, 42, 43, 50]),)

4th try:
0 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 40, 41, 48, 51, 53]),)
1 (array([37, 42, 43, 50]),)
2 (array([ 1, 16, 25, 26, 30, 46]),)
3 (array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 23,
       27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)


y0 = decreasing list
1st try:
0 (array([ 1, 16, 25, 26, 30, 46]),)
1 (array([ 0,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19,
       20, 22, 23, 27, 28, 29, 32, 35, 36, 37, 38, 39, 42, 43, 44, 45, 47,
       48, 49, 50, 52]),)
2 (array([ 8, 21, 24, 31, 33, 34, 40, 41, 51, 53]),)
2nd try:
0 (array([ 0,  1,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20,
       23, 25, 27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)
1 (array([37, 42, 43, 50]),)
2 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 40, 41, 48, 51, 53]),)
3 (array([16, 26, 30, 46]),)

3rd try:
0 (array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 23,
       27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)
1 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 37, 40, 41, 42, 43, 48, 50, 51,
       53]),)
2 (array([ 1, 16, 25, 26, 30, 46]),)

4th:
0 (array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 23,
       27, 28, 29, 32, 35, 36, 38, 39, 44, 45, 47, 49, 52]),)
1 (array([ 1, 16, 25, 26, 30, 46]),)
2 (array([ 2,  5,  8, 21, 22, 24, 31, 33, 34, 37, 40, 41, 42, 43, 48, 50, 51,
       53]),)


In [8]:
butterfly = np.array([[-5,0],
                      [-3.34, 1.67], 
                      [-3.34, 0], 
                      [-3.34, -1.67], 
                      [-1.67, 0], 
                      [0,0], 
                      [1.67,0], 
                      [3.34, -1.67],
                      [3.34, 0],
                      [3.34, 1.67],
                      [5,0],
                      [10,10]])
from sklearn.metrics.pairwise import euclidean_distances
butterfly_dist_mat=euclidean_distances(butterfly,butterfly)

In [137]:
#del EKNNclus
import importlib
import EKNNclus
EKNNclus = importlib.reload(EKNNclus)
n = len(butterfly)
clus = EKNNclus.EKNNclus_Th(butterfly, K=4, y0 = list(range(n)), D = butterfly_dist_mat)
print(clus)

0 1 10 4
0 2 2 2
0 3 0 2
[0 0 0 0 0 0 1 1 1 1 1 1]
