# Two models (k-o'means & Belief function based) on Sushi preference

In [1]:
from read import read_voter_file, read_score_file, read_order_file
from tools import all_mass_init, all_certain_mass_init, flatten_pref_mass_mat
from beliefKMeans import k_means, silhouette_score, _k_means_single

import numpy as np

vMap = read_voter_file("../data/sushi3-2016/sushi3.udata", 10)
#read_score_file("../data/sushi3-2016/sushi3b.5000.10.score", vMap, 100)
read_order_file("../data/sushi3-2016/sushi3a.5000.10.order", vMap, 10)
n_item = 10
n_sample = len(vMap)
vector_size = 4
n_pref_pair = int(n_item*(n_item-1)/2)
X = np.empty((n_sample, n_pref_pair, vector_size),dtype = object)


[1546, 1535, 1406, 1457, 1380, 1447, 1412, 1353, 1321, 1244, 1297, 1213, 1194, 1118, 1112, 1077, 1012, 1016, 968, 957, 939, 945, 868, 857, 841, 847, 785, 775, 699, 694, 696, 619, 512, 567, 560, 545, 500, 532, 509, 453, 433, 468, 413, 334, 336, 327, 358, 366, 347, 348, 355, 385, 287, 282, 231, 199, 214, 218, 219, 236, 219, 234, 213, 215, 234, 155, 142, 138, 135, 155, 141, 164, 169, 133, 165, 148, 144, 131, 150, 153, 78, 67, 88, 50, 66, 80, 52, 77, 85, 84, 74, 80, 76, 75, 72, 95, 68, 79, 75, 77]
[0, 1, 3, 5, 6, 2, 4, 7, 8, 10, 9, 11, 12, 13, 14, 15, 17, 16]
1
[3182]


In [2]:
for k,v in vMap.items():
    X[k] = flatten_pref_mass_mat(all_certain_mass_init(vMap[k].get_order_a(),10))

In [3]:
X.shape

(10, 45, 4)

In [ ]:
labels, inertia, centers, distances, iterNb = _k_means_single(X, 3, init='k_means',max_iter = 5, verbose = True)

/home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/iBelief/distance.py:18: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if D== None:


centers initialized, shape:(3, 45, 4)
Initialization complete
E step:
labels after step E: [2 1 0 0 2 2 0 1 1 0]
M step:
[4 3 3]
> /home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/beliefKMeans.py(277)_centers_dense()
-> centers[i] = _fusion(X[np.where(labels == i)[0]], strategy = 2)
(Pdb) c
new center for 0 calculated
> /home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/beliefKMeans.py(276)_centers_dense()
-> pdb.set_trace()
(Pdb) c
new center for 1 calculated
> /home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/beliefKMeans.py(277)_centers_dense()
-> centers[i] = _fusion(X[np.where(labels == i)[0]], strategy = 2)
(Pdb) c
new center for 2 calculated
Iteration  0, inertia 2.978 
Best inertia: None
best result updated
E step:
labels after step E: [2 1 0 0 2 2 0 1 1 1]
M step:
[3 4 3]
> /home/yzhang/ThesisWork/Program/sushiPref/sushiCode/sushiCode/beliefKMeans.py(277)_centers_dense()
-> centers[i] = _fusion(X[np.where(labels == i)[0]], strategy = 2)
(Pdb

In [8]:
centers

NameError: name 'centers' is not defined

experiments on artificial data
    

In [2]:
from tools import all_mass_init, all_certain_mass_init, flatten_pref_mass_mat
from singleBeliefKMeans import k_means, silhouette_score, _k_means_single
import numpy as np
from iBelief.distance import JousselmeDistance

In [2]:
def read_mass_file(file):
    masses = np.empty((0,16))
    with open(file) as f:
        for line in f:
            masses = np.vstack((masses, np.array([float(i) for i in line.split()])))
    return masses

In [3]:
X = read_mass_file("/home/yzhang/ThesisWork/Program/sushiPref/sushiCode/data/sushi3-2016/artificiel_mass.data")

In [4]:
X = X[:6]

In [5]:
X

array([[ 0.        ,  0.3385673 ,  0.00475236,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.6554754 ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.00120499],
       [ 0.        ,  0.131232  ,  0.07621001,  0.        ,  0.2876665 ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.5048914 ],
       [ 0.        ,  0.07812018,  0.8427176 ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.01211108,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.06705113],
       [ 0.        ,  0.        ,  0.08955104,  0.        ,  0.2305491 ,
         0.        ,  0.        ,  0.        ,  0.290527  ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.3893729 ],
       [ 0.        ,  0.19548   ,  0

In [6]:
labels, inertia, centers, distances, iterNb = _k_means_single(X, 5, init='k_means',max_iter =20, verbose = True)

centers initialized, shape:(5, 16)
Initialization complete
E step:
labels after step E: [0 2 4 0 1 2 1 1 0 2 2 2 0 2 3 1 2 2 2 1 2 0 1 1 3 1 0 3 2 2 1 2 2 3 2 2 4
 1 2 0 0 3 1 3 0 2 4 4 4 3 2 3 3 0 4 0 4 0 0 1 2 0 1 4 1 2 2 4 2 0 2 1 0 4
 2 1 4 1 2 3 4 2 4 3 2 2 1 4 3 1 4 1 2 3 1 2 2 2 3 1 2 1 2 1 3 2 0 2 1 1 2
 2 1 0 0 2 1 3 0 2 1 2 0 3 1 1 4 1 3 4 2 4 2 2 2 0 2 2 3 2 1 2 4 1 2 4 1 0
 2 4 2 0 2 1 2 2 2 1 1 2 0 1 1 2 1 4 2 3 2 2 1 2 4 1 0 2 0 2 1 1 2 1 4 1 2
 3 2 2 2 4 0 2 2 1 1 4 1 0 2 0]
M step:
[30 50 73 21 26]
new center for 0 calculated
new center for 1 calculated
new center for 2 calculated
new center for 3 calculated
new center for 4 calculated
Iteration  0, inertia 48.729 
Best inertia: None
best result updated
E step:
labels after step E: [0 2 4 0 4 2 1 1 0 2 2 2 0 2 3 1 2 2 2 1 2 0 1 4 0 1 0 3 2 2 1 2 2 3 2 2 4
 1 2 0 0 3 1 3 0 2 4 4 4 3 2 3 3 0 4 0 4 0 0 1 2 0 1 4 1 2 2 4 2 0 2 4 2 4
 2 1 1 1 2 3 4 2 4 0 2 2 2 4 3 1 4 1 2 3 1 2 2 2 3 1 2 1 2 1 3 2 0 2 1 1 2
 2 1 0 0 2 1 3 0 

In [53]:
m1 = np.array([0, 0, 0.4705075, 0, 0, 0, 0, 0.5294925])
m2 = np.array([0, 0, 0, 0, 0.09643297, 0, 0, 0.9035670])
m3 = np.array([0, 0.7657971, 0,    0, 0 ,   0,    0, 0.2342029])
m4 = np.array([0, 0.6981436, 0,  0, 0,    0,    0, 0.3018564])
m5 = np.array([0, 0.0673869, 0,  0, 0,  0 ,   0, 0.9326131])
m6 = np.array([0, 0.6210247, 0,  0, 0,   0 ,   0, 0.3789753])
m7 = np.array([0, 0, 0.1509951 ,   0, 0,   0,    0, 0.8490049])
m8 = np.array([0, 0.3991368, 0,  0, 0,  0, 0, 0.6008632])
m9 = np.array([0, 0, 0.5140124 , 0, 0, 0 ,0, 0.4859876])
m10 = np.array([0, 0.3716902, 0, 0, 0,  0 , 0 ,0.6283098])

In [52]:
from center_cal import one_mass_center_calculate
def euclid_center(m_N):
    return np.mean(m_N, axis = 0)
def two_center_close(m_N):
    return np.allclose(one_mass_center_calculate(m_N), euclid_center(m_N))


In [55]:
m_N = np.vstack((m1,m2,m3,m4, m5))
two_center_close(m_N)

True

conclusion: J_O combinaition on singleton is merely mean value.

In [17]:
m1 = np.array([0, 0, 0.4705075, 0, 0, 0, 0, 0.5294925])
m2 = np.array([0, 0, 0, 0, 0.09643297, 0, 0, 0.9035670])
m3 = np.array([0, 0.7657971, 0,    0, 0 ,   0,    0, 0.2342029])
m_N = np.vstack((m1,m2))
c1 = one_mass_center_calculate(m_N)
print(c1)
print("center1", one_mass_center_calculate(np.vstack((c1, m3))))
print("center2", one_mass_center_calculate(np.vstack((m1,m2,m3))))

[  3.75000000e-09   3.74999990e-09   2.35253754e-01   2.18476031e-16
   4.82164887e-02   4.96031787e-16   5.24580379e-16   7.16529750e-01]
center1 [  1.87499998e-09   3.82898552e-01   1.17626877e-01   1.67921232e-16
   2.41082444e-02  -5.41233725e-17   3.78863607e-16   4.75366325e-01]
center2 [  2.49999999e-09   2.55265703e-01   1.56835836e-01  -2.27992228e-16
   3.21443258e-02  -1.39174386e-16   1.74860126e-16   5.55754133e-01]


conclusion: J_O combination is not associative (it's normal, like average method)

In [15]:
m1 = np.array([0.50075975, 0.000000, 0.0000000 ,   0, 0.00000000, 0.4992402, 0.0000000, 0.0000000])
m2 = np.array([0, 0, 0, 0, 0.09643297, 0, 0, 0.9035670])
m_N = np.vstack((m1,m2))
print(m_N)
center = one_mass_center_calculate(m_N)
print(center)

[[ 0.50075975  0.          0.          0.          0.          0.4992402
   0.          0.        ]
 [ 0.          0.          0.          0.          0.09643297  0.          0.
   0.903567  ]]
[  2.50379885e-01   9.99999979e-09   9.99999981e-09   5.41233725e-16
   4.82164950e-02   2.49620100e-01   4.95437025e-16   4.51783500e-01]


In [18]:
m1 = np.array([0.1, 0.1, 0.1 , 0.1, 0.1, 0.1, 0.1, 0.3])
m2 = np.array([0, 0, 0, 0, 0, 0, 0, 1])
m_N = np.vstack((m1,m2))
print(m_N)
center = one_mass_center_calculate(m_N)
print(center)

[[ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.3]
 [ 0.   0.   0.   0.   0.   0.   0.   1. ]]
[ 0.05  0.05  0.05  0.05  0.05  0.05  0.05  0.65]


In [57]:
m1 = np.array([1.0, 0, 0 , 0, 0, 0, 0, 0])
m2 = np.array([0, 0, 0, 0, 0, 0, 0, 1.0])
m_N = np.vstack((m1,m2))
print(m_N)
center = one_mass_center_calculate(m_N)
print(center)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]
[  5.00000000e-01  -2.06184276e-16  -2.25216671e-16   5.89211219e-16
  -2.03012210e-16   5.44802299e-16   5.82867088e-16   5.00000000e-01]


In [31]:
m1 = np.array([0.1, 0.1, 0.1 , 0.1, 0.1, 0.1, 0.1, 0.3])
m2 = np.array([0, 0, 0.3, 0.2, 0, 0, 0, 0.5])
m3 = np.array([0,0,0,0,0,0,1, 0])
m_N = np.vstack((m1,m2,m3))
print(m_N)
center = one_mass_center_calculate(m_N)
print(center)

[[ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.3]
 [ 0.   0.   0.3  0.2  0.   0.   0.   0.5]
 [ 0.   0.   0.   0.   0.   0.   1.   0. ]]
[ 0.03333333  0.03333333  0.13333333  0.1         0.03333333  0.03333333
  0.36666667  0.26666667]
